### PR TITLE
Improved egif_lib coverage by extending the gif encoder test harness

### PR DESCRIPTION
**Pull request by bshastry**
This PR extends the gif encoder fuzzer harness by
  - treating the fuzzer input as an RGB stream and encoding this into a Gif file
  - TODO: How much space to allocate for the encoded gif file buffer? Can this be pre-computed?
     - Allocating a hard-coded size of 4KB (4096 bytes) but I'm afraid this might overshoot the limit and mask potential buffer overwrites in the gif library.

### CODE REVIEW

**Comment by viniul** [comment]
LGTM :)
Idea to work around the size problem: Maybe we can adapt `stub_output_writer` to return `0` if we would write past the allocated size?

**Comment by bshastry** [comment]
> Maybe we can adapt stub_output_writer to return 0 if we would write past the allocated size?

Detecting out of bounds write is not the problem, Asan will do that. Question I had: What is the upper bound for the size of memory for encoding a gif?

My best answer to this was set it to 4k which is quite ad hoc.

This harness didn't find any bugs for me. Should we send it to ossfuzz?

**Comment by viniul** [comment]
I see - I was thinking: What if allocate too little memory, i.e. the case that say 4k is not enough? Then our current harness would cause an oob write that is not giflib's fault, no?

**Comment by viniul** [comment]
Come to think about it: What do you think of allocating a little bit smaller buffer (1/2k or so) and simply allocating more memory once more is needed (which we will know from stub_output_writer)?

**Comment by bshastry** [comment]
> Come to think about it: What do you think of allocating a little bit smaller buffer (1/2k or so) and simply allocating more memory once more is needed (which we will know from stub_output_writer)?

That's a better idea than what I had in mind. The stub output writer should essentially emulate fwrite.

The out of bounds should not be an issue if we do this.

**Comment by viniul** [comment]
Let me implement that and send a PR :)

**Comment by viniul** [comment]
I will merge this PR for now and then send another PR - is that okay for you?

**Pull request merged**
